/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 26-oct.-2022 05:48:21 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */


SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `censado` CASCADE
;

DROP TABLE IF EXISTS `ct_tipos_documentos` CASCADE
;

DROP TABLE IF EXISTS `Especie` CASCADE
;

DROP TABLE IF EXISTS `Familia` CASCADE
;

DROP TABLE IF EXISTS `Funcionarios` CASCADE
;

DROP TABLE IF EXISTS `Planta` CASCADE
;

DROP TABLE IF EXISTS `Sector_zona` CASCADE
;

/* Create Tables */

CREATE TABLE `censado`
(
	`id_censo` INT NOT NULL AUTO_INCREMENT,
	`Fecha_creacion` DATE NOT NULL,
	`Zona1` INT NOT NULL,
	`id_funcionario` INT NOT NULL,
	`id_planta` INT NOT NULL,
	CONSTRAINT `PK_censado` PRIMARY KEY (`id_censo` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `ct_tipos_documentos`
(
	`id_tip_doc` INT NOT NULL AUTO_INCREMENT,
	`tipo_documento` VARCHAR(30) NOT NULL,
	`iniciales_tip_doc` VARCHAR(3) NOT NULL,
	CONSTRAINT `PK_ct_tipos_documentos` PRIMARY KEY (`id_tip_doc` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `Especie`
(
	`id_especie` INT NOT NULL AUTO_INCREMENT,
	`nombre_especie` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Especie` PRIMARY KEY (`id_especie` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `Familia`
(
	`id_Familia` INT NOT NULL AUTO_INCREMENT,
	`Nombre_familia` VARCHAR(50) NOT NULL,
	`id_especie` INT NULL,
	CONSTRAINT `PK_Familia` PRIMARY KEY (`id_Familia` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `Funcionarios`
(
	`id_funcionario` INT NOT NULL AUTO_INCREMENT,
	`Nombre_f` VARCHAR(25) NOT NULL,
	`Nombre2` VARCHAR(25) NULL,
	`Apellido1` VARCHAR(25) NOT NULL,
	`Apellido2` VARCHAR(25) NULL,
	`Telefono_f` DECIMAL(12,0) NULL,
	`Direccion_f` VARCHAR(50) NULL,
	`Cargo_funcionario` VARCHAR(50) NOT NULL,
	`Vigencia` BOOL NOT NULL,
	`tip_doc_funcionartio` INT NULL,
	`num_doc_funcionario` VARCHAR(15) NULL,
	CONSTRAINT `PK_Funcionarios` PRIMARY KEY (`id_funcionario` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `Planta`
(
	`id_planta` INT NOT NULL AUTO_INCREMENT,
	`id_Familia` INT NULL,
	`Nombre_planta` VARCHAR(50) NOT NULL,
	`Descripcion_planta` VARCHAR(255) NULL,
	CONSTRAINT `PK_Planta` PRIMARY KEY (`id_planta` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `Sector_zona`
(
	`id_zona` INT NOT NULL AUTO_INCREMENT,
	`zona` VARCHAR(50) NULL,
	`Tipo_clima` VARCHAR(50) NULL,
	`Tipo_terreno` VARCHAR(50) NULL,
	CONSTRAINT `PK_Sector_zona` PRIMARY KEY (`id_zona` ASC)
)
ENGINE=InnoDB
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `censado` 
 ADD INDEX `IXFK_censado_Funcionarios` (`id_funcionario` ASC)
;

ALTER TABLE `censado` 
 ADD INDEX `IXFK_censado_Planta` (`id_planta` ASC)
;

ALTER TABLE `censado` 
 ADD INDEX `IXFK_censado_Sector_zona` (`id_planta` ASC)
;

ALTER TABLE `Familia` 
 ADD INDEX `IXFK_Familia_Especie` (`id_especie` ASC)
;

ALTER TABLE `Planta` 
 ADD INDEX `IXFK_Planta_Familia` (`id_Familia` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `censado` 
 ADD CONSTRAINT `FK_censado_Funcionarios`
	FOREIGN KEY (`id_funcionario`) REFERENCES `Funcionarios` (`id_funcionario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `censado` 
 ADD CONSTRAINT `FK_censado_Planta`
	FOREIGN KEY (`id_planta`) REFERENCES `Planta` (`id_planta`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `censado` 
 ADD CONSTRAINT `FK_censado_Sector_zona`
	FOREIGN KEY (`id_planta`) REFERENCES `Sector_zona` (`id_zona`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Familia` 
 ADD CONSTRAINT `FK_Familia_Especie`
	FOREIGN KEY (`id_especie`) REFERENCES `Especie` (`id_especie`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Funcionarios` 
 ADD CONSTRAINT `FK_Funcionarios_ct_tipos_documentos`
	FOREIGN KEY (`tip_doc_funcionartio`) REFERENCES `ct_tipos_documentos` (`id_tip_doc`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Planta` 
 ADD CONSTRAINT `FK_Planta_Familia`
	FOREIGN KEY (`id_Familia`) REFERENCES `Familia` (`id_Familia`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
